osx_image: xcode12.4
language: objective-c

# safelist
branches:
    only:
        - master

script:
- set -o pipefail && xcodebuild test -destination $IOS_DESTINATION -workspace Example/SimplifiedNotificationCenter.xcworkspace -scheme SimplifiedNotificationCenter-Example ONLY_ACTIVE_ARCH=NO | xcpretty

