osx_image: xcode10.1
language: objective-c

# safelist
branches:
    only:
        - master

script:
- set -o pipefail && xcodebuild test -destination $IOS_DESTINATION -workspace Example/SimplifiedNotificationCenter.xcworkspace -scheme SimplifiedNotificationCenter-Example -sdk $IOS_SDK ONLY_ACTIVE_ARCH=NO | xcpretty

