name: tests

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  tests:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Run Tests
      run: swift test